//
// Created by Nicolas Bush on 15/06/2022.
//

import Foundation

class Report {
	
	/**
	 Ecrit le rapport de génération
	 - Parameters:
	   - toDirectory: le repertoire de destination
	   - cliVersion: la version du CLI
	   - config: la configuration
       - languages: List of exported languages
	 - Throws:
	 */
	func writeReport(toDirectory dir: URL, cliVersion : String, config: POEditorConfiguration, languages : [Language]) throws {
		let data = try _getData(
		  version: cliVersion,
		  config: config,
          languages : languages
		)
		let destinationURL = dir.appendingPathComponent("translations_export.txt")
		try data.write(to: destinationURL, options: .atomicWrite)
	}
	
	
	/**
	 Retourne les données du rapport
	 - Parameters:
	   - version: la version du CLI
	   - config: la configuration
	 - Returns: des Data
	 - Throws:
	 */
    private func _getData(version : String, config: POEditorConfiguration, languages : [Language]) throws -> Data {
		
		let df = ISO8601DateFormatter()
		df.formatOptions = .withInternetDateTime
		
		
		let str = """
translations generation report
================
- generated by: poeditor CLI v\(version)
- date: \(df.string(from: Date()))
- apiPath: \(config.apiPath)
- apiToken: \(config.apiToken)
- projectId: \(config.projectId)
- languages: \(languages.map { $0.code}.joined(separator: ", "))
"""
		
		guard let data = str.data(using: .utf8) else {
			throw RuntimeError("Can't generate report")
		}
		
		return data
	}
	
	
	
	
	
}
